USE CompanyDB;
GO


--CREATE TABLE EMPLOYEE (
--    Ssn          CHAR(9)       NOT NULL,
--    Bdate        DATE,
--    Fname        VARCHAR(50),
--    Minit        CHAR(1),
--    Lname        VARCHAR(50),
--    Address      VARCHAR(100),
--    Sex          CHAR(1),
--    Salary       DECIMAL(10,2),
--    Depanumber   INT,
--    SuperviseSsn CHAR(9),
--    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Ssn)
--);

--CREATE TABLE DEPARTMENT (
--Depanumber INT NOT NULL,
--Depaname VARCHAR(50) NOT NULL,
--StartDate DATE,
--ManageSsn CHAR(9),
--CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Depanumber)
--);

--CREATE TABLE LOCATION (
--Depanumber INT NOT NULL,
--Locations VARCHAR(50) NOT NULL,
--CONSTRAINT PK_LOCATION PRIMARY KEY (Depanumber, Locations)
--);

--CREATE TABLE PROJECT (
--Pnumber INT NOT NULL,
--Pname VARCHAR(50),
--Location VARCHAR(50),
--Depanumber INT,
--CONSTRAINT PK_PROJECT PRIMARY KEY (Pnumber)
--);

--CREATE TABLE DEPENDENT (
--Depename VARCHAR(50) NOT NULL,
--Sex CHAR(1),
--Birthday DATE,
--Relationship VARCHAR(30),
--Ssn CHAR(9) NOT NULL,
--CONSTRAINT PK_DEPENDENT PRIMARY KEY (Ssn, Depename)
--);

--CREATE TABLE WORK_ON(
--Ssn CHAR(9) NOT NULL,
--Pnumber INT NOT NULL,
--Hours DECIMAL(5,2),
--CONSTRAINT PK_WORK_ON PRIMARY KEY (Ssn, Pnumber)
--);
--GO

--ALTER TABLE EMPLOYEE
--    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
--        FOREIGN KEY (Depanumber) REFERENCES DEPARTMENT(Depanumber);

--ALTER TABLE EMPLOYEE
--    ADD CONSTRAINT FK_EMPLOYEE_SUPERVISOR
--        FOREIGN KEY (SuperviseSsn) REFERENCES EMPLOYEE(Ssn);

--ALTER TABLE DEPARTMENT
--    ADD CONSTRAINT FK_DEPARTMENT_MANAGER
--        FOREIGN KEY (ManageSsn) REFERENCES EMPLOYEE(Ssn);

--ALTER TABLE LOCATION
--    ADD CONSTRAINT FK_LOCATION_DEPARTMENT
--        FOREIGN KEY (Depanumber) REFERENCES DEPARTMENT (Depanumber);

--ALTER TABLE PROJECT
--    ADD CONSTRAINT FK_PROJECT_DEPARTMENT
--        FOREIGN KEY (Depanumber) REFERENCES DEPARTMENT(Depanumber);

--ALTER TABLE DEPENDENT
--    ADD CONSTRAINT FK_DEPENDENT_EMPLOYEE
--        FOREIGN KEY (Ssn) REFERENCES EMPLOYEE(Ssn);

--ALTER TABLE WORK_ON
--    ADD CONSTRAINT FK_WORK_ON_EMPLOYEE
--        FOREIGN KEY (Ssn) REFERENCES EMPLOYEE(Ssn);

--ALTER TABLE WORK_ON
--    ADD CONSTRAINT FK_WORK_ON_PROJECT
--        FOREIGN KEY (Pnumber) REFERENCES PROJECT(Pnumber);
--GO